AllCops:
  DisplayCopNames: true

Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - '**/spec/**/*'
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_special
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_special
Layout/IndentationConsistency:
  EnforcedStyle: rails
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  SupportedStyles:
    - indented
    - indented_relative_to_receiver
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
    - '**/*.rake'
    - '*.gemspec'
Metrics/LineLength:
  Max: 120
  IgnoredPatterns:
    - '^\W*\#'
Metrics/ModuleLength:
  Exclude:
    - '**/spec/**/*'

Naming/FileName:
  Exclude:
    - 'lib/reload-attribute.rb'

Style/AccessModifierDeclarations:
  Enabled: false
Style/Documentation:
  Exclude:
    - spec/**/*
Style/DocumentationMethod:
  Enabled: true
  RequireForNonPublicMethods: true
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'
Style/DoubleNegation:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
